name: Static Site

on:
  push:
    branches:
      - main  # Set a branch to deploy
      - gha-service-account
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download font assets
        # use fonts in stable releases
        run: |
          mkdir -p assets/fonts/
          curl -L https://github.com/Myriad-Dreamin/typst-book/releases/download/v0.1.2/font-assets.tar.gz | tar -xvz -C assets/fonts
          curl -L https://use.fontawesome.com/releases/v6.4.2/fontawesome-free-6.4.2-desktop.zip -o fontawesome-free-6.4.2-desktop.zip
          unzip fontawesome-free-6.4.2-desktop.zip
          cp -v -r fontawesome-free-6.4.2-desktop/otfs/* assets/fonts/
      - name: Download & install typst-book
        run: |
          curl -L https://github.com/Myriad-Dreamin/typst-book/releases/download/v0.1.3/typst-book-x86_64-unknown-linux-gnu.tar.gz | tar -xvz
          chmod +x typst-book-x86_64-unknown-linux-gnu/bin/typst-book
          sudo cp typst-book-x86_64-unknown-linux-gnu/bin/typst-book /usr/bin/typst-book
      - name: Build Book
        run: typst-book build --font-path assets/fonts -w . -d ./dist .

      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/701757388294/locations/global/workloadIdentityPools/bruh/providers/bruh'
          service_account: 'yuanxiang@innate-infusion-418917.iam.gserviceaccount.com'

      # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'dist'
          destination: 'yuanxiang'
          parent: false
